### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/geospatial#117]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] base_geoengine - By @yvaucher - #123 
- [x] base_geoengine_demo - By @yvaucher - #123 
- [ ] geoengine_base_geolocalize
- [ ] geoengine_geoname_geocoder
- [ ] geoengine_maplausanne
- [ ] geoengine_partner - By @petrus-v - #135 
- [ ] geoengine_project
- [ ] geoengine_sale
- [ ] geoengine_swisstopo

**Comment by petrus-v** [comment]
I've started geoengine_partner migration here: #135

**Comment by ecino** [comment]
Are there any plans for `geoengine_geoname_geocoder` and `geoengine_base_geolocalize` migration?
