### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/geospatial#156]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] base_geoengine - By @asaunier - #178
- [x] base_geoengine_demo - By @Tonow-c2c - #177
- [ ] geoengine_base_geolocalize  @josueBulle #216
- [ ] geoengine_geoname_geocoder
- [ ] geoengine_maplausanne
- [ ] geoengine_partner  @josueBulle #215
- [ ] geoengine_project
- [ ] geoengine_sale
- [x] geoengine_swisstopo @asaunier #188

**Comment by pnajman-modoolar** [comment]
Hello, we would like to help with migration ...

**Comment by yvaucher** [comment]
hello @pnajman-modoolar ,

Migration has not been started yet. To start the migration the first thing to migrate is the module base_geoengine. And to test it base_geoengine_demo should be done too as it can be used for testing purpose.
An other priority, maybe more accessible is to make travis happy, as we have a lot of js lint to do on the branch 10.0. Once done in 10.0 we will then apply it to the branch 11.0.

So, feel free to add your contribution and tell us if you start on anything.

I might work on the migration during OCA code sprint, but it takes place on 1st octobre 2018.

**Comment by dek-odoo** [comment]
Great..
Is the migration going to be with OpenLayers 3 ?

**Comment by yvaucher** [comment]
@dek-odoo we did the port to OL3 in Odoo 9.0 which remains as a separate branch: https://github.com/OCA/geospatial/tree/9.0-ol3

And since Odoo 10.0 it is alread there.

If the question is about an upgrade to OpenLayers 4, yes I think we should be up to date. AFAIK the API between OL3 and OL4 doesn't change much.

**Comment by dek-odoo** [comment]
@yvaucher 
I was probably thinking about [this issue](https://github.com/OCA/geospatial/issues/143)

**Comment by max3903** [comment]
Hi all,

@osi-scampbell is looking at the modules in 10.0 to determine what we need to migrate for https://github.com/OCA/field-service.

**Comment by Maartincm** [comment]
Any news on this migration? Im willing to help!

**Comment by emagdalenaC2i** [comment]
There is a PR for the migration of base_geoengine - By @asaunier - #178 
There is a PR for the migration of base_geoengine_demo - By @Tonow-c2c - #177

**Comment by emagdalenaC2i** [comment]
Please, check geoengine_swisstopo @asaunier #188 that is already merged
