### ISSUE TITLE
Geospatial Roadmap for Field Service

### ISSUE THREAD

**Issue by max3903** [OCA/geospatial#184]
https://github.com/OCA/field-service/issues/53

# Phase 1a

- [x] Dots on a map
- [ ] Color-coded dots and symbols based on any field of order/location
- [x] Swap basemap (Streets, Light colored)

# Phase 1b

- [ ] Show on mobile device with my current location
- [x] Swap basemap (Satellite)

# Phase 2

- [x] Display territory/branch/district/region (FSM objects) polygons
- [ ] Assemble territory polygons based on ZIP codes/states/country
- [x] Point and polygon: Being able to answer what is the territory of a location
- [ ] Modify boundaries by polygons editing → editing territory/branch/district/region

# Phase 3

- [ ] Route distance calculation (probably with Google for accuracy)
- [ ] Route optimization
     - [ ] Use API for different kind of optimization
     - [ ] Display straight lines between points to show the sequence of a route
- [ ] Mobile: Show driving directions between points (optimized path to reach the location of the next order)

# Phase 4

- [ ] Display location structure with lines between locations using parent

# Phase 5

- [ ] Drivetime polygon
- [ ] Realtime mapping: track vehicles, workers, worker/equipment statuses

**Comment by GuM0x1a** [comment]
@max3903 Great Job.

**Comment by babatoko** [comment]
Hi, where are you on this roadmap ? I mean witch phase is the current.

**Comment by brian10048** [comment]
#264 is a start for Phase 3: route optimization and distance calculation.  This PR needs review
