### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/geospatial#314]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
- [x] base_geoengine - By @kouffsamuel - #338
- [ ] base_geoengine_demo - By @kouffsamuel - #329
- [x] geoengine_base_geolocalize - By @sbejaoui - #332
- [x] geoengine_partner - By @sbejaoui - #331
- [x] web_view_leaflet_map - By @legalsylvain - #342
- [x] web_view_leaflet_map_partner - By @legalsylvain - #342

**Comment by ferdymercury** [comment]
can this be closed?
