### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/geospatial#56]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] geoengine_project
- [ ] geoengine_sale
- [x] base_geoengine @yvaucher https://github.com/OCA/geospatial/pull/60
- [x] base_geoengine_demo @yvaucher https://github.com/OCA/geospatial/pull/60
- [ ] geoengine_geoname_geocoder
- [ ] geoengine_base_geolocalize @JonathanNEMRY https://github.com/OCA/geospatial/pull/144
- [x] geoengine_partner @yvaucher https://github.com/OCA/geospatial/pull/128

**Comment by yvaucher** [comment]
I'm starting to work on migration of base_geoengine for 9.0
@lmignon

**Comment by lmignon** [comment]
Thank you in advance @yvaucher I've never found the time to finalize the migration to OpenLayer3 started on https://github.com/acsone/geospatial/tree/8.0-ol3-lmi

**Comment by lmignon** [comment]
@yvaucher I'm a little bit afraid but it seems that it will not be possible to use these addons on an 9.0 enterprise since we depend of 'web' and in enterprise 'web' is not lgpl. I'm even more worried to see that it will no more be possible to use 'AGPL' addons extending the module 'web' in enterprise. In the case of the module 'web', enterprise is not an extend of community but a relicenced fork.

**Comment by yvaucher** [comment]
@lmignon For now I'm working on porting it to community version,  I succeeded to display the maps in the widget but I'm having hard time trying to show the map on Geoengine view. You might already want to test with an enterprise if the widget are well displayed.

https://github.com/OCA/geospatial/pull/60

**Comment by isabellerichard** [comment]
I've installed geoengine_project and geoengine_sale on Odoo 9.0 Enterprise, maps are well displayed, but project.project and sale.order views are not translated anymore. Context is not passed correctly to method fields_view_get, probably a problem of compatibility between old and new api signatures (context content is inside variable "toolbar").

**Comment by pedrobaeza** [comment]
Please don't dirty this issue. Write a new one. I delete both comments.
